--1) MOSTRE O NOME DO DPTO, CIDADE QUE ELE ESTÁ--
SELECT D.DEPARTMENT_NAME,
       C.CITY
FROM DEPARTMENTS D
JOIN LOCATIONS C ON (C.LOCATION_ID = D.LOCATION_ID);

--2) RELATORIO QUE MOSTRE O NOME DE TODOS OS EMPREGADOS Q TRABALHAM EM LONDON
SELECT E.FIRST_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS ON (E.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID)
JOIN LOCATIONS ON (LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID)
WHERE LOCATIONS.CITY = 'London';

--  --
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID
FROM EMPLOYEES ORDER BY 1;

--3) NOME DO EMPREGADO E O NOME DO GERENTE DESSE EMPREGADO (AUTO RELACIONAMENTO)
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.SALARY, E.MANAGER_ID, G.FIRST_NAME
FROM EMPLOYEES E
JOIN EMPLOYEES G ON (G.EMPLOYEE_ID = E.MANAGER_ID) -- TEM QUE SER CHAVE ESTRANGEIRA DELES
ORDER BY 1;

-- MOSTRAR JOIN MESMO QUE TENHA NULL
-- SE O ELEMENTO QUE TEM NULL ESTÁ A ESQUERDA USE O LEFT, SE ESTÁ A DIREITA USSE O RIGHT
--AGORA TBM TRAZ O STEVEN KING Q O MANAGER É NULL
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.SALARY, E.MANAGER_ID, G.FIRST_NAME
FROM EMPLOYEES E
LEFT OUTER JOIN EMPLOYEES G ON (G.EMPLOYEE_ID = E.MANAGER_ID) 
ORDER BY 1;

SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
ORDER BY 1;

--SE FOR POSSIVEL TER NULL EM AMBOS OS LADOS USE O FULL OUTER
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
FULL OUTER JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
ORDER BY 1;